<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var \Magento\Framework\View\Element\Template $this */

/** @var \Magento\Backend\Block\Template $block */

/** @var \Licentia\Panda\Helper\Data $helper */
$helper = $this->helper('\Licentia\Panda\Helper\Data');

$paramsEncode = $block->getRequest()->getParams();
$paramsEncode['m'] = $block->getRequest()->getModuleName();
$paramsEncode['c'] = $block->getRequest()->getControllerName();
$paramsEncode['a'] = $block->getRequest()->getActionName();
$paramsEncode = json_encode($paramsEncode);

?>
<script type="text/javascript">
    <?php if ($helper->delayAjaxLoads()) : ?>
    require(['jquery', 'domReady!'], function ($) {
        var autorespondersTimer = setInterval(function () {
            if (localStorage["mage-cache-storage"] !== '{}') {
                clearInterval(autorespondersTimer);
                <?php endif; ?>
                $.ajax({
                    url: '<?= /* @noEscape */ $block->getUrl('panda/service/process') ?>',
                    type: "POST",
                    dataType: 'json',
                    data:  <?= /* @noEscape */ $paramsEncode ?>
                });
                <?php if ($helper->delayAjaxLoads()) : ?>
            }
        }, 500);
    });
    <?php endif; ?>
</script>