<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var \Magento\Framework\View\Element\Template $this */

/** @var \Magento\Backend\Block\Template $block */

/** @var \Licentia\Panda\Helper\Data $helper */
$helper = $this->helper('\Licentia\Panda\Helper\Data');

$paramsEncode = $block->getRequest()->getParams();
$paramsEncode['m'] = $block->getRequest()->getModuleName();
$paramsEncode['c'] = $block->getRequest()->getControllerName();
$paramsEncode['a'] = $block->getRequest()->getActionName();
$paramsEncode = json_encode($paramsEncode);

?>
<script type="text/javascript">
    <?php if ($helper->delayAjaxLoads()) : ?>
    require(['jquery', 'domReady!'], function ($) {
        var autorespondersTimer = setInterval(function () {
            if (localStorage["mage-cache-storage"] !== '{}') {
                clearInterval(autorespondersTimer);
                <?php endif; ?>
                $.ajax({
                    url: '<?= /* @noEscape */ $block->getUrl('panda/service/process') ?>',
                    type: "POST",
                    dataType: 'json',
                    data: <?= /* @noEscape */ $paramsEncode ?>
                });
                <?php if ($helper->delayAjaxLoads()) : ?>
            }
        }, 500);
    });
    <?php endif; ?>
</script>