<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

?>
<div class="block block-subscribe">
    <div class="block-title">
        <strong><span><?= /* @noEscape */
                __('Newsletter') ?></span></strong>
    </div>
    <form action="<?= /* @noEscape */
    $block->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter"><?= /* @noEscape */
                    __('Sign Up for Our Newsletter:') ?></label>
            </div>
            <div class="input-box">
                <input type="text" name="email" id="newsletter"
                       title="<?= $block->escapeHtmlAttr(__('Sign up for our newsletter')) ?>"
                       class="input-text required-entry validate-email"/>
            </div>
            <div>
                <?= $block->getChildHtml('customer.form.newsletter.extra') ?>
            </div>
            <div class="actions">
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" class="button">
                    <span><span><?= /* @noEscape */
                            __('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>
</div>
