<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

?>

<form class="form form-newsletter-manage" data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= /* @noEscape */
                __('Subscription option') ?></span></legend>
        <br>
        <div class="field choice">
            <input type="hidden" value="<?= $block->escapeHtmlAttr($block->getSubscriber()->getCode()) ?>" name="code">
            <input type="checkbox" name="is_subscribed" id="subscription" value="1"
                <?php if ($block->getSubscriber()->isActive()) :
                    ?> checked="checked"<?php
                endif; ?> class="checkbox">
            <label for="subscription" class="label"> <span><?= /* @noEscape */
                    __('General Subscription') ?></span>
            </label>
        </div>
        <?= $block->getChildHtml() ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= /* @noEscape */
            __('Save') ?>" class="action save primary">
                <span><?= /* @noEscape */
                    __('Save') ?></span>
            </button>
        </div>
    </div>
</form>
