<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var $block \Magento\Backend\Block\Template */

?>

<form class="form form-newsletter-manage" data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      action="<?= $block->escapeUrl($block->getAction()) ?>" method="post" id="form-validate">
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= /* @noEscape */
                __('Subscription option') ?></span></legend>
        <br>
        <div class="field choice">
            <input type="hidden" value="<?= $block->escapeHtmlAttr($block->getSubscriber()->getCode()) ?>" name="code">
            <input type="checkbox" name="is_subscribed" id="subscription" value="1"
                <?php if ($block->getSubscriber()->isActive()) :
                    ?> checked="checked"<?php
                endif; ?> class="checkbox">
            <label for="subscription" class="label"> <span><?= /* @noEscape */
                    __('General Subscription') ?></span>
            </label>
        </div>
        <?= $block->getChildHtml() ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?= /* @noEscape */
            __('Save') ?>" class="action save primary">
                <span><?= /* @noEscape */
                    __('Save') ?></span>
            </button>
        </div>
    </div>
</form>
