<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var \Licentia\Panda\Block\Popup $block */

if (!$block->hasActivePopups()) {
    return '';
}

/** @var \Licentia\Panda\Helper\Data $helper */
$helper = $this->helper('\Licentia\Panda\Helper\Data');

$params = [
    'c' => $block->getRequest()
                 ->getControllerName(),
    'e' => $block->getRequest()
                 ->getParam('panda_emulated_popup', 0),
    'a' => $block->getRequest()
                 ->getActionName(),
    'm' => $block->getRequest()
                 ->getModuleName(),
    'i' => $block->getRequest()
                 ->getParam('id', 0),
];
$params = json_encode($params);
?>
<script type="text/javascript">
    require(['jquery', 'pandaPopup', 'domReady!'], function ($) {
        <?php if ($helper->delayAjaxLoads()) : ?>
        var timePopup = setInterval(function () {
            if (localStorage["mage-cache-storage"] !== '{}') {
                clearInterval(timePopup);
                <?php endif; ?>
                $.ajax({
                    url: '<?= /* @noEscape */ $block->getUrl('panda/block/window') ?>',
                    type: "POST",
                    context: document.body,
                    dataType: 'html',
                    success: function (responseText) {
                        $("#panda_popup_placeholder").html(responseText);
                    },
                    data: {
                        'params': '<?= /* @noEscape */ $params ?>',
                        'identifier': window.location.pathname,
                        'referer': document.referrer
                    }
                });
                <?php if ($helper->delayAjaxLoads()) : ?>
            }
        }, 500);
        <?php endif; ?>
    });
</script>
<div id="panda_popup_placeholder"></div>