<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var \Licentia\Panda\Block\Subscribe $block */

/** @var \Licentia\Forms\Model\Forms $form */
$form = $block->getFormForManagePage();

if (!$form) {
    return '';
}

$elements = $form->getActiveElements();
?>
<script type="text/javascript">
    require(['jquery', 'domReady!'], function ($) {

        $('form.form.form-newsletter-manage')
            .attr('data-mage-init', '{"validation": {"errorClass": "mage-error"}}')
            .attr('enctype', 'multipart/form-data');

    });
</script>
<div class="block-contents">
    <?php if (!$form->getEnableTemplate()) : ?>
        <fieldset class="fieldset">
            <?php if ($form->getTitle()) : ?>
                <legend class="legend"><span><?= /* @noEscape */
                        __($form->getTitle()) ?></span></legend><br/>
            <?php endif; ?>
            <?php if ($form->getDescription()) : ?>
                <div class="field note no-label"><?= /* @noEscape */
                    __($form->getDescription()) ?></div>
            <?php endif; ?>
            <?php foreach ($elements as $element) : ?>

                <?= /* @noEscape */
                $block->getFormRender()->getElementHtml($element) ?><?php
            endforeach; ?>

        </fieldset>
    <?php else :
        ?><?= /* @noEscape */
        $block->getFormRender()->parseTemplate() ?><?php
    endif; ?>
</div>
