<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var \Licentia\Panda\Block\Subscribe $block */

/** @var \Licentia\Forms\Model\Forms $form */
$form = $block->getFormForManagePage();

if (!$form) {
    return '';
}

$elements = $form->getActiveElements();
?>
<script type="text/javascript">
    require(['jquery', 'domReady!'], function ($) {

        $('form.form.form-newsletter-manage')
            .attr('data-mage-init', '{"validation": {"errorClass": "mage-error"}}')
            .attr('enctype', 'multipart/form-data');

    });
</script>
<div class="block-contents">
    <?php if (!$form->getEnableTemplate()) : ?>
        <fieldset class="fieldset">
            <?php if ($form->getTitle()) : ?>
                <legend class="legend"><span><?= /* @noEscape */
                        __($form->getTitle()) ?></span></legend><br/>
            <?php endif; ?>
            <?php if ($form->getDescription()) : ?>
                <div class="field note no-label"><?= /* @noEscape */
                    __($form->getDescription()) ?></div>
            <?php endif; ?>
            <?php foreach ($elements as $element) : ?>

                <?= /* @noEscape */
                $block->getFormRender()->getElementHtml($element) ?><?php
            endforeach; ?>

        </fieldset>
    <?php else :
        ?><?= /* @noEscape */
        $block->getFormRender()->parseTemplate() ?><?php
    endif; ?>
</div>
