<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

$coupons = $block->getCoupons();

?>
<div class="admin__old">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= /* @noEscape */
            __('Customer Coupons List') ?></span>
    </div>
    <br/>
    <table class="data-grid" id="customerCouponsGrid">
        <thead>
        <tr>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Order ID') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Order Date') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Created At') ?>*</span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Valid Until') ?>*</span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Order Status') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Name') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Code') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Description') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Used') ?></span></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($coupons as $coupon) : ?>
            <tr class=" ">
                <td><a target="_blank" href="<?= /* @noEscape */
                    $block->getUrl(
                        'sales/order/view',
                        ['order_id' => $coupon['order_id']]
                    ) ?>">
                        <?= $coupon['order_id'] ?></a></td>
                <td><?= $block->escapeHtml($block->formatDate($coupon['created_at'], 2)) ?></td>
                <td><?= $block->escapeHtml($block->formatDate($coupon['from_date'], 2)) ?></td>
                <td><?= $block->escapeHtml($block->formatDate($coupon['to_date'], 2)) ?></td>
                <td><?= $block->escapeHtml($coupon['state']) ?></td>
                <td><?= $block->escapeHtml($coupon['name']) ?></td>
                <td><?= $block->escapeHtml($coupon['code']) ?></td>
                <td><?= $block->escapeHtml($coupon['description']) ?></td>
                <td><?= $block->escapeHtml(strlen($coupon['code']) > 0 ? __('Yes') : __('No')) ?></td>
            </tr>
        <?php endforeach; ?>
        <?php if (count($coupons) == 0) : ?>
            <tr class=" ">
                <td colspan="7"><?= /* @noEscape */
                    __('No Data') ?></td>
            </tr>

        <?php endif; ?>
        </tbody>
    </table>
    <br/>
    <small><em>*<?= /* @noEscape */
            __('Current rule values') ?></em></small>

</div>
