<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var $block \Magento\Backend\Block\Template */

$coupons = $block->getCoupons();

?>
<div class="admin__old">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= /* @noEscape */
            __('Customer Coupons List') ?></span>
    </div>
    <br/>
    <table class="data-grid" id="customerCouponsGrid">
        <thead>
        <tr>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Order ID') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Order Date') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Created At') ?>*</span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Valid Until') ?>*</span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Order Status') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Name') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Code') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Description') ?></span></th>
            <th class="data-grid-th not-sort"><span><?= /* @noEscape */
                    __('Used') ?></span></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($coupons as $coupon) : ?>
            <tr class=" ">
                <td><a target="_blank" href="<?= /* @noEscape */
                    $block->getUrl(
                        'sales/order/view',
                        ['order_id' => $coupon['order_id']]
                    ) ?>">
                        <?= $coupon['order_id'] ?></a></td>
                <td><?= $block->escapeHtml($block->formatDate($coupon['created_at'], 2)) ?></td>
                <td><?= $block->escapeHtml($block->formatDate($coupon['from_date'], 2)) ?></td>
                <td><?= $block->escapeHtml($block->formatDate($coupon['to_date'], 2)) ?></td>
                <td><?= $block->escapeHtml($coupon['state']) ?></td>
                <td><?= $block->escapeHtml($coupon['name']) ?></td>
                <td><?= $block->escapeHtml($coupon['code']) ?></td>
                <td><?= $block->escapeHtml($coupon['description']) ?></td>
                <td><?= $block->escapeHtml(strlen($coupon['code']) > 0 ? __('Yes') : __('No')) ?></td>
            </tr>
        <?php endforeach; ?>
        <?php if (count($coupons) == 0) : ?>
            <tr class=" ">
                <td colspan="7"><?= /* @noEscape */
                    __('No Data') ?></td>
            </tr>

        <?php endif; ?>
        </tbody>
    </table>
    <br/>
    <small><em>*<?= /* @noEscape */
            __('Current rule values') ?></em></small>

</div>
