<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

/** @var \Licentia\Panda\Helper\Debug $helper */
$helper = $this->helper('Licentia\Panda\Helper\Debug');

$info = $helper->getDebugInfo();

?>

<style>
    div.grid {
        width: 100%;
        border: 1px solid #e04f00;
        margin: 20px 0;
    }

    .admin__scope-old .grid {
        padding: 0;
    }

    div.grid table td, div.grid table th {
        padding: 10px;
        word-break: break-all;
    }

    div.grid table th {
        color: #ffffff;
    }

    div.grid table tr.headings {
        background-color: #e04f00;
    }

    div.grid table tr:nth-child(even) {
        background-color: #dedede;
    }

    div.grid.error {
        border: 1px solid red;
    }

    div.grid.error table tr.headings {
        background-color: red;
    }
</style>

<div class="grid">
    <table cellspacing="0" class="data">
        <thead>
        <tr class="headings">
            <th colspan="2"><span class="nobr"><?= /* @noEscape */
                    __('Debug Information') ?></span></th>
        </tr>
        </thead>
        <tbody id="">
        <?php foreach ($info as $key => $line) : ?>
            <tr>
                <td style="width: 30%"><?= $block->escapeHtml($key) ?></td>
                <td><?= $block->escapeHtml($line) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
