<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var $block \Magento\Backend\Block\Template */

/** @var \Licentia\Panda\Helper\Debug $helper */
$helper = $this->helper('Licentia\Panda\Helper\Debug');

$info = $helper->getDebugInfo();
$error = $helper->getErrorLogFileContents();

?>

<style>
    div.grid {
        width: 100%;
        border: 1px solid #e04f00;
        margin: 20px 0;
    }

    .admin__scope-old .grid {
        padding: 0;
    }

    div.grid table td, div.grid table th {
        padding: 10px;
        word-break: break-all;
    }

    div.grid table th {
        color: #ffffff;
    }

    div.grid table tr.headings {
        background-color: #e04f00;
    }

    div.grid table tr:nth-child(even) {
        background-color: #dedede;
    }

    div.grid.error {
        border: 1px solid red;
    }

    div.grid.error table tr.headings {
        background-color: red;
    }
</style>

<div class="grid">
    <table cellspacing="0" class="data">
        <thead>
        <tr class="headings">
            <th colspan="2"><span class="nobr"><?= /* @noEscape */
                    __('Debug Information') ?></span></th>
        </tr>
        </thead>
        <tbody id="">
        <?php foreach ($info as $key => $line) : ?>
            <tr>
                <td style="width: 30%"><?= $block->escapeHtml($key) ?></td>
                <td><?= $block->escapeHtml($line) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="grid error">
    <table cellspacing="0" class="data">
        <thead>
        <tr class="headings">
            <th colspan="2"><span class="nobr"><?= /* @noEscape */
                    __('Error Log Contents') ?></span></th>
        </tr>
        </thead>
        <tbody id="">
        <tr>
            <td colspan="2"><textarea style="width: 100%; height: 550px;"><?= $block->escapeHtml($error) ?></textarea>
            </td>
        </tr>
        </tbody>
    </table>
</div>
