<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

$triggers = $block->getAutorespondersTriggersDetails();

$tabs = [];
foreach ($triggers as $k => $trigger) {
    $name = explode('-', $trigger['name']);
    $trigger['code'] = $k;
    $tabs[trim($name[0])][] = $trigger;
}

?>
<div class="new_autoresponder">
    <script type="text/javascript">
        require(["jquery", "jquery/ui", 'domReady!'], function ($) {

            $('ul.tabs li').click(function () {
                var tab_id = $(this).attr('data-tab');

                $('ul.tabs li').removeClass('current');
                $('.tab-content').removeClass('current');

                $(this).addClass('current');
                $("#" + tab_id).addClass('current');
            })

        });
    </script>
    <ul class="tabs">
        <?php $i = 0;
        foreach ($tabs as $name => $trigger) : ?>
            <li class="tab-link <?= $i == 0 ? 'current' : ''; ?>"
                data-tab="tab-<?= str_replace(' ', '', $name) ?>"><?= /* @noEscape */
                __($name) ?></li>
            <?php $i++;

        endforeach; ?>
    </ul>

    <?php $i = 0;
    foreach ($tabs as $name => $trigger) : ?>
        <div class="tab-content <?= $i == 0 ? 'current' : ''; ?>"
             id="tab-<?= str_replace(' ', '', $name); ?>">
            <ul class="list">
                <?php foreach ($trigger as $key => $info) : ?>

                    <li class="list-item">
                        <strong><a href="<?= $block->getUrl(
                                '*/*/edit',
                                ['event' => $info['code']]
                            ) ?>"><?= $block->escapeHtml(str_replace($name . ' - ', '', $info['name'])) ?></a></strong>
                        <p> <?= $info['description'] ?></p>
                    </li>

                <?php endforeach; ?>
            </ul>
        </div>
        <?php $i++;

    endforeach; ?>
</div>
