<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var \Magento\Backend\Block\Template $block */

$actions = $block->getAutorespondersActions();

?>

<link href="<?= $block->getViewFileUrl('Licentia_Panda::styles/style.css') ?>"
      rel="stylesheet"
      type="text/css">
<script type="text/javascript">
    var panda_url_action = '<?= $block->getUrl(
        'panda/autoresponders/tree',
        [
            'autoresponder_id' => $block->getAutoresponder()->getId(),
        ]
    )?>';

    require(['jquery', 'Licentia_Panda/js/tree', 'domReady!'], function ($, n) {
        n('.tree').tree({
            'img_url': '<?= $block->getViewFileUrl('Licentia_Panda::images/load.gif')?>'
        });
    });
</script>
<body>
<div id="loading-mask">
    <div data-role="spinner" class="admin__data-grid-loading-mask">
        <div class="spinner">
            <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
        </div>
    </div>
</div>
<div style="float:left; width:200px;">

    <?php foreach ($actions as $action) : ?>
        <div class="draggable" id="<?= /* @noEscape */
        $action['id'] ?>">
            <?= $action['name'] ?><span><?= /* @noEscape */
                $action['description'] ?></span></div>

    <?php endforeach; ?>

</div>
<div style="text-align: center; min-width: 900px">
    <?= $block->getTree(); ?>
</div>
</body>