<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var $block \Magento\Backend\Block\Template */

echo $block->getFormHtml() ?>
<style type="text/css">
    table.form-list tr:nth-child(even) {
        background-color: #dedede;
    }

    table.form-list th {
        background-color: #666;
        color: white;
        padding: 10px;
    }

    table.form-list td {
        padding: 10px;
    }

</style>

<div class="entry-edit">
    <legend class="admin__legend legend">
        <span><?= /* @noEscape */
            __('Template Variables') ?></span>
    </legend>
    <table class="form-list" style="width: 400px" cellspacing="0">
        <tbody>
        <tr>
            <th style="width: 200px">
                <label"><?= __('Code') ?>
            </th>
            <th style="width: 200px">
                <label"><?= __('Value for') ?>
            </th>
        </tr>
        <tr>
            <td style="width: 200px">
                {title}
            </td>
            <td style="width: 200px">
                <?= __('Form Title'); ?>
            </td>
        </tr>
        <tr>
            <td style="width: 200px">
                {description}
            </td>
            <td style="width: 200px">
                <?= __('Form Description'); ?>
            </td>
        </tr>
        <tr>
            <td style="width: 200px">
                {button}
            </td>
            <td style="width: 200px">
                <?= __('Form Submit Button'); ?>
            </td>
        </tr>
        <?php foreach ($block->getFormElements() as $element) : ?>
            <tr>
                <td style="width: 200px">
                    {{element_<?= $element->getId(); ?>}}
                </td>
                <td style="width: 200px">
                    Form Element: <?= $element->getName(); ?>
                </td>
            </tr>

        <?php endforeach; ?>

        </tbody>
    </table>
    <p></p>
    <p><?= __('Note: You can use {{element_X hide="label,hint"}} to hide the form label and hint') ?>

    </p>
</div>
