<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

$stats = $block->getRegistry()->registry('panda_stats');
$report = $block->getRegistry()->registry('panda_report');
/** @var \Licentia\Panda\Model\Campaigns $campaign */
$campaign = $block->getRegistry()->registry('panda_report_campaign');

$b = $stats->getStats($campaign->getId(), 'browser');
$p = $stats->getStats($campaign->getId(), 'platform');

$jsonBrowsers = Zend_Json::encode($b);
$jsonPlatforms = Zend_Json::encode($p);
?>
<div class="grid">
    <table cellspacing="0" class="data data-grid admin__control-table ">
        <thead>
        <tr class="headings">
            <th class=" no-link last"><span class="nobr"><?= /* @noEscape */
                    __('Email Client') ?></span></th>
        </tr>
        </thead>
        <tbody id="">
        <tr>
            <td class="last" style="text-align:center">

                <?php if (count($p) > 1) : ?>
                    <script type="text/javascript">
                        //<![CDATA[

                        require(['jquery'], function ($) {

                            google.charts.load("visualization", "1", {packages: ["corechart"]});
                            google.charts.setOnLoadCallback(drawChart);

                            $(window).resize(function () {
                                var container = document.getElementById("chart_platforms").firstChild.firstChild;
                                container.style.width = "100%";
                                drawChart();
                            });


                            google.charts.load("visualization", "1", {packages: ["corechart"]});
                            google.charts.setOnLoadCallback(drawChart);

                            function drawChart() {
                                var data = google.visualization.arrayToDataTable(<?= $jsonPlatforms ?>);

                                var options = {
                                    backgroundColor: {fill: 'transparent'},
                                    width: (jQuery(window).width() - 550),
                                    height: 400,
                                    bar: {groupWidth: '80%'},
                                    colors: ['#e0440e', '#f3b49f']
                                };

                                var chart = new google.visualization.ColumnChart(document.getElementById('chart_platforms'));
                                chart.draw(data, options);
                            }

                        });
                        //]]>

                    </script>

                    <div id="chart_platforms" style="width: 100%"></div>
                <?php else :
                    ?><p><?= /* @noEscape */
                __('No Data') ?></p>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<div class="grid">
    <table cellspacing="0" class="data data-grid admin__control-table ">
        <thead>
        <tr class="headings">
            <th class=" no-link last"><span class="nobr"><?= /* @noEscape */
                    __('Browsers') ?></span></th>
        </tr>
        </thead>
        <tbody id="">
        <tr>
            <td class="last" style="text-align:center">
                <?php if (count($b) > 1) : ?>
                    <script type="text/javascript">
                        //<![CDATA[

                        require(['jquery', 'domReady!'], function ($) {


                            google.charts.load("visualization", "1", {packages: ["corechart"]});
                            google.charts.setOnLoadCallback(drawChart);

                            $(window).resize(function () {
                                var container = document.getElementById("chart_browsers").firstChild.firstChild;
                                container.style.width = "100%";
                                drawChart();
                            });

                            function drawChart() {
                                var data = google.visualization.arrayToDataTable(<?= $jsonBrowsers ?>);

                                var options = {
                                    backgroundColor: {fill: 'transparent'},
                                    height: 400,
                                    width: (jQuery(window).width() - 550),
                                    bar: {groupWidth: '80%'},
                                    colors: ['#e0440e', '#f3b49f']
                                };

                                var chart = new google.visualization.ColumnChart(document.getElementById('chart_browsers'));
                                chart.draw(data, options);
                            }
                        });
                        //]]>

                    </script>
                <?php else :
                    ?><p><?= /* @noEscape */
                __('No Data') ?></p>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>