<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var $block \Magento\Backend\Block\Template */

$stats = $block->getRegistry()->registry('panda_stats');
$report = $block->getRegistry()->registry('panda_report');
/** @var \Licentia\Panda\Model\Campaigns $campaign */
$campaign = $block->getRegistry()->registry('panda_report_campaign');

$b = $stats->getStats($campaign->getId(), 'browser');
$p = $stats->getStats($campaign->getId(), 'platform');

$jsonBrowsers = Zend_Json::encode($b);
$jsonPlatforms = Zend_Json::encode($p);
?>
<div class="grid">
    <table cellspacing="0" class="data data-grid admin__control-table ">
        <thead>
        <tr class="headings">
            <th class=" no-link last"><span class="nobr"><?= /* @noEscape */
                    __('Email Client') ?></span></th>
        </tr>
        </thead>
        <tbody id="">
        <tr>
            <td class="last" style="text-align:center">

                <?php if (count($p) > 1) : ?>
                    <script type="text/javascript">
                        //<![CDATA[

                        require(['jquery'], function ($) {

                            google.charts.load("visualization", "1", {packages: ["corechart"]});
                            google.charts.setOnLoadCallback(drawChart);

                            $(window).resize(function () {
                                var container = document.getElementById("chart_platforms").firstChild.firstChild;
                                container.style.width = "100%";
                                drawChart();
                            });


                            google.charts.load("visualization", "1", {packages: ["corechart"]});
                            google.charts.setOnLoadCallback(drawChart);

                            function drawChart() {
                                var data = google.visualization.arrayToDataTable(<?= $jsonPlatforms ?>);

                                var options = {
                                    backgroundColor: {fill: 'transparent'},
                                    width: (jQuery(window).width() - 550),
                                    height: 400,
                                    bar: {groupWidth: '80%'},
                                    colors: ['#e0440e', '#f3b49f']
                                };

                                var chart = new google.visualization.ColumnChart(document.getElementById('chart_platforms'));
                                chart.draw(data, options);
                            }

                        });
                        //]]>

                    </script>

                    <div id="chart_platforms" style="width: 100%"></div>
                <?php else :
                    ?><p><?= /* @noEscape */
                __('No Data') ?></p>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>

<div class="grid">
    <table cellspacing="0" class="data data-grid admin__control-table ">
        <thead>
        <tr class="headings">
            <th class=" no-link last"><span class="nobr"><?= /* @noEscape */
                    __('Browsers') ?></span></th>
        </tr>
        </thead>
        <tbody id="">
        <tr>
            <td class="last" style="text-align:center">
                <?php if (count($b) > 1) : ?>
                    <script type="text/javascript">
                        //<![CDATA[

                        require(['jquery', 'domReady!'], function ($) {


                            google.charts.load("visualization", "1", {packages: ["corechart"]});
                            google.charts.setOnLoadCallback(drawChart);

                            $(window).resize(function () {
                                var container = document.getElementById("chart_browsers").firstChild.firstChild;
                                container.style.width = "100%";
                                drawChart();
                            });

                            function drawChart() {
                                var data = google.visualization.arrayToDataTable(<?= $jsonBrowsers ?>);

                                var options = {
                                    backgroundColor: {fill: 'transparent'},
                                    height: 400,
                                    width: (jQuery(window).width() - 550),
                                    bar: {groupWidth: '80%'},
                                    colors: ['#e0440e', '#f3b49f']
                                };

                                var chart = new google.visualization.ColumnChart(document.getElementById('chart_browsers'));
                                chart.draw(data, options);
                            }
                        });
                        //]]>

                    </script>
                <?php else :
                    ?><p><?= /* @noEscape */
                __('No Data') ?></p>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>