<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

$stats = $block->getRegistry()->registry('panda_stats');
$report = $block->getRegistry()->registry('panda_report');
/** @var \Licentia\Panda\Model\Campaigns $campaign */
$campaign = $block->getRegistry()->registry('panda_report_campaign');

$c = $stats->getStats($campaign->getId(), 'country');
$c[0][0] = 'Country';
$jsonCountries = Zend_Json::encode($c);

?>

<div class="grid">
    <table cellspacing="0" class="data data-grid admin__control-table ">
        <thead>
        <tr class="headings">
            <th><?= /* @noEscape */
                __('Countries') ?></th>
        </tr>
        </thead>
        <tbody id="">
        <tr>
            <td class="last" style="text-align:center">
                <?php if (count($c) > 1) : ?>
                    <div id="chart_countries"></div>
                    <script type="text/javascript">
                        //<![CDATA[
                        require(['jquery'], function ($) {

                            google.charts.load('current', {
                                'packages': ['geochart'],
                                'mapsApiKey': '<?= $block->getGoogleApi() ?>'
                            });
                            google.charts.setOnLoadCallback(drawChart);

                            function drawChart() {
                                var data = google.visualization.arrayToDataTable(<?= $jsonCountries ?>);
                                var options = {
                                    backgroundColor: {fill: 'transparent'},
                                    width: (jQuery(window).width() - 650),
                                    fontSize: 11,
                                    legend: {position: 'top', textStyle: {color: 'red', fontSize: 12}}
                                };

                                var chart = new google.visualization.GeoChart(document.getElementById('chart_countries'));
                                chart.draw(data, options);
                            }

                            $(window).resize(function () {
                                var container = document.getElementById("chart_countries").firstChild.firstChild;
                                container.style.width = "100%";
                                drawChart();
                            });
                        });
                        //]]>
                    </script>
                <?php else :
                    ?><p><?= /* @noEscape */
                __('No Data') ?></p>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>