<?php
/*
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

$stats = $block->getRegistry()->registry('panda_stats');
$report = $block->getRegistry()->registry('panda_report');
/** @var \Licentia\Panda\Model\Campaigns $campaign */
$campaign = $block->getRegistry()->registry('panda_report_campaign');

$l = $stats->getLinks($campaign->getId());
$jsonLinks = Zend_Json::encode($l);

$height = count($l) * 60;
?>
<div class="grid">
    <table cellspacing="0" class="data data-grid admin__control-table ">
        <thead>
        <tr class="headings">
            <th class=" no-link last"><span class="nobr"><?= /* @noEscape */
                    __('Links') ?></span></th>
        </tr>
        </thead>
        <tbody id="">
        <tr>
            <td class="last" style="text-align:center">
                <?php if (count($l) > 1) : ?>
                    <script type="text/javascript">
                        //<![CDATA[

                        require(['jquery'], function ($) {
                            google.charts.load("visualization", "1", {packages: ["corechart"]});
                            google.charts.setOnLoadCallback(drawChart);


                            $(window).resize(function () {
                                var container = document.getElementById("chart_links").firstChild.firstChild;
                                container.style.width = "100%";
                                drawChart();
                            });

                            function drawChart() {
                                var data = google.visualization.arrayToDataTable(<?= $jsonLinks ?>);

                                var options = {
                                    backgroundColor: {fill: 'transparent'},
                                    width: (jQuery(window).width() - 550),
                                    chartArea: {
                                        height: data.getNumberOfRows() * 30,
                                        width: '40%'
                                    },
                                    height: <?= $height; ?>,
                                    bar: {groupWidth: '80%'},
                                    colors: ['#e0440e', '#f3b49f']
                                };

                                var chart = new google.visualization.BarChart(document.getElementById('chart_links'));
                                chart.draw(data, options);
                            }

                        });
                        //]]>


                    </script>
                <?php else :
                    ?><p><?= /* @noEscape */
                __('No Data') ?></p>
                <?php endif; ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>