<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */
/** @var \Licentia\Panda\Helper\Data $pandaHelper */

$pandaHelper = $this->helper(\Licentia\Panda\Helper\Data::class);

/** @var \Licentia\Panda\Model\Subscribers $subscriber */
$subscriber = $pandaHelper->getRegistry()->registry('panda_subscriber');

/** @var \Magento\Quote\Model\Quote $quote */
$quote = $pandaHelper->getSubscriberQuote();

if (!$quote) {
    return; //No products
}

/** @var Magento\Catalog\Helper\Image $imgHelper */
$imgHelper = $this->helper(\Magento\Catalog\Helper\Image::class);

$items = $quote->getItemsCollection();
?>
<table width="620" border="0" cellspacing="0" cellpadding="5" class="message order-details">
    <tr>
        <th colspan="2"><?= /* @noEscape */
            __('Product') ?></th>
        <th align="right"><?= /* @noEscape */
            __('Qty') ?></th>
        <th align="right"><?= /* @noEscape */
            __('Price') ?></th>
    </tr>
    <?php

    /** @var \Magento\Quote\Model\Quote\Item $item */
    foreach ($items as $item) {

        /** @var \Magento\Catalog\Model\Product $_product */
        $_product = $item->getProduct();
        ?>
        <tr>
            <td><img src="<?= $block->escapeHtmlAttr($imgHelper->init($_product, 'mini_cart_product_thumbnail')
                                                               ->resize(75, 75)
                                                               ->getUrl()); ?>" width="75" height="75"
                     alt="<?= $block->escapeHtmlAttr($_product->getName()) ?>"/>
            </td>
            <td><?= $block->escapeHtml($_product->getName()) ?></td>
            <td align="right"><?= $block->escapeHtml($item->getQty()) ?></td>
            <td align="right">
                <?= /* @noEscape */
                $this->helper(\Magento\Framework\Pricing\Helper\Data::class)
                     ->currency(
                         $item->getRowTotalInclTax(),
                         true,
                         false
                     ); ?>
            </td>
        </tr>
    <?php } ?>
    <tr style="background-color:#f4f4f4;">
        <td colspan="4" align="right"><?= /* @noEscape */
            __('Subtotal') ?></td>
        <td align="right"> <?= /* @noEscape */
            $this->helper(\Magento\Framework\Pricing\Helper\Data::class)
                 ->currency(
                     $quote->getSubtotal(),
                     true,
                     false
                 ); ?></td>
    </tr>
    <tr style="background-color:#e7e7e7;">
        <td colspan="5" align="center" style="font-size: 18px;">
            <a style="color: #0a6c9f" href="<?= /* @noEscape */
            $block->getUrl(
                'checkout/cart',
                ['_nosid' => true,]
            ) ?>">
                <?= /* @noEscape */
                __('Restore my Cart!') ?>
            </a>
        </td>
    </tr>
</table>
