<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var \Licentia\Panda\Block\Coupons $block */
if ($block->getRule()) :
    if (!$block->canShowCoupon($block->getRule()->getCode(), $block->getWidgetData('hide_if_expired'))) {
        return false;
    }

    ?>
    <?= /* @noEscape */
    $block->getRule()->getCode();

    if ($block->getWidgetData('countdown')) {
        $couponId = $block->getRule()->getId();
        $message = str_replace(
            '{countdown}',
            $block->getWidgetData('countdown_format'),
            $block->getWidgetData('countdown_message')
        );
        ?>
        <p class="panda countdown widget" id="coupon_countdown<?= /* @noEscape */
        $couponId ?>">&nbsp;</p>
        <script type="text/javascript">
            var countDownDate = new Date("<?= /* @noEscape */ $block->expiresAt($block->getRule()->getCode()) ?>")
                .getTime();
            var x = setInterval(function () {
                var now = new Date().getTime();
                var distance = countDownDate - now;

                var string = "<?= /* @noEscape */  __($message); ?>";
                var mapObj = {
                    '{d}': Math.floor(distance / (1000 * 60 * 60 * 24)),
                    '{h}': Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)),
                    '{m}': Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60)),
                    '{s}': Math.floor((distance % (1000 * 60)) / 1000)
                };
                string = string.replace(/\{d\}|\{h\}|\{m\}|\{s\}/gi, function (matched) {
                    return mapObj[matched];
                });

                document.getElementById("coupon_countdown<?= /* @noEscape */ $couponId ?>").innerHTML = string;
                if (distance < 0) {
                    clearInterval(x);
                    document.getElementById("coupon_countdown<?= /* @noEscape */ $couponId ?>").innerHTML = "<?= /* @noEscape */  __('Expired!') ?>";
                }
            }, 1000);
        </script>
    <?php } ?>
<?php endif; ?>