<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */

?>

<div class="entry-edit">
    <fieldset class="fieldset admin__fieldset " id="params_fieldset">
        <legend class="admin__legend legend">
            <span><?= /* @noEscape */
                __('Load template') ?></span>
        </legend>
        <br>

        <table class="form-list" cellspacing="0">
            <tbody>
            <tr>
                <td class="label">
                    <label for="template_select">
                        <?= __('Template') ?>
                        <span class="required">*</span> </label>
                </td>
                <td class="value">
                    <?php if (count($block->getTemplateOptions()) == 0) :
                        ?><?= __(
                        "You don't have any template"
                    ) ?><?php
                    else : ?>
                        <select id="template_selecta" name="code" class="select required-entry">

                            <?php foreach ($block->getTemplateOptions() as $_option) : ?>
                                <option value="<?= $block->escapeHtmlAttr($_option['value']) ?>"><?= $block->escapeHtml($_option['label']) ?></option>
                            <?php endforeach; ?>
                        </select>

                    <?php endif; ?>
                    <?php if (count($block->getTemplateOptions()) > 0) : ?>
                        <button style="" onclick="templateControla.load();" class="scalable save" type="button">
                            <span>Load Template</span>
                        </button>
                    <?php endif; ?>
                </td>
            </tr>

            </tbody>
        </table>
    </fieldset>
</div>
<?= $block->getBlockHtml('formkey') ?>
<?= $block->getFormHtml() ?>


<script type="text/javascript">
    require(['prototype'], function () {

        //<![CDATA[
        templateControla = {
            load: function () {
                new Ajax.Request('<?= $block->getUrl('*/campaigns/template') ?>', {
                    parameters: {code: $('template_select').value, field: '<?= $block->getTemplateField() ?>'},
                    area: $('email_template_load_form'),
                    onComplete: function (transport) {
                        if (transport.responseText.isJSON()) {
                            var fields = $H(transport.responseText.evalJSON());
                            fields.each(function (pair) {
                                if ($(pair.key)) {
                                    $(pair.key).value = pair.value.strip();
                                    if (tinyMCE.activeEditor) {
                                        tinyMCE.activeEditor.setContent(pair.value.strip());
                                    }
                                }
                            }.bind(this));
                        }
                    }.bind(this)
                });
            }

        };
//]]>

    });


</script>
