<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */
?>

<?php

$url = $block->getUrl(
    'panda/campaigns/preview',
    [
        'c'  => 1,
        'id' => $block->getCampaign()
                      ->getId(),
    ]
);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= $block->escapeHtmlAttr($block->getLang()) ?>">
<head>
    <?= $block->getChildHtml('head') ?>
    <style type="text/css">
        html, body {
            height: 100%;
        }
    </style>
</head>
<body id="html-body" style="background:#fff;">
<div id="preview" class="cms-revision-preview">
    <div class="toolbar">
        <p class="switcher">
            <?= __('Subscriber Id/Email') ?>
            <input type="text" id="subscriber_id" class="input-text">
            <button onClick="document.getElementById('preview_iframe').src = '<?= $url ?>sid/'+document.getElementById('subscriber_id').value;">
                <span>   <?= __('Preview') ?></span></button>
        </p>
    </div>
    <iframe name="preview_iframe" src="<?= $block->escapeHtmlAttr($url) ?>" id="preview_iframe"
            style="width:100%; height:100%; min-height: 550px;" frameborder="0"></iframe>
</div>
<div id="loading-mask" style="display:none">
    <p class="loader" id="loading_mask_loader"><br/><?= /* @noEscape */
        __('Please wait...') ?></p>
</div>
</body>
</html>