<?php
/**
 * Copyright (C) Licentia, Unipessoal LDA
 *
 * NOTICE OF LICENSE
 *
 *  This source file is subject to the EULA
 *  that is bundled with this package in the file LICENSE.txt.
 *  It is also available through the world-wide-web at this URL:
 *  https://www.greenflyingpanda.com/panda-license.txt
 *
 *  @title      Licentia Panda - Magento® Sales Automation Extension
 *  @package    Licentia
 *  @author     Bento Vilas Boas <bento@licentia.pt>
 *  @copyright  Copyright (c) Licentia - https://licentia.pt
 *  @license    https://www.greenflyingpanda.com/panda-license.txt
 *
 */

/** @var $block \Magento\Backend\Block\Template */
?>

<?= $block->getFormHtml() ?>
<?= $block->getBlockHtml('formkey') ?>


<script type="text/javascript">
    require(['prototype'], function () {

        recurringControl = {
            load: function () {
                recur = $('recurring').value;

                all_fields = ['recurring_day', 'run_times', 'run_until', 'recurring_unique', 'recurring_daily', 'recurring_first_run', 'recurring_monthly', 'recurring_month', 'deploy_at', 'recurring_time', 'end_method'];

                switch (recur) {
                    case '0':
                        fields = ['deploy_at'];
                        break;
                    case 'd':
                        fields = ['recurring_daily', 'recurring_unique', 'recurring_time', 'run_times', 'run_until', 'recurring_first_run', 'end_method'];
                        break;
                    case 'w':
                        fields = ['recurring_day', 'recurring_unique', 'recurring_time', 'run_times', 'run_until', 'recurring_first_run', 'end_method'];
                        break;
                    case 'm':
                        fields = ['recurring_monthly', 'recurring_unique', 'recurring_time', 'run_times', 'run_until', 'recurring_first_run', 'end_method'];
                        break;
                    case 'y':
                        fields = ['recurring_monthly', 'recurring_unique', 'recurring_month', 'recurring_time', 'run_times', 'run_until', 'recurring_first_run', 'end_method'];
                        break;
                    default:

                }

                for (i = 0; i < all_fields.length; i++) {
                    $(all_fields[i]).up('div').up('div').hide();
                }

                for (i = 0; i < fields.length; i++) {
                    $(fields[i]).up('div').up('div').show();
                }

                if (recur == '0') {
                    $$('.saveandsendbutton').each(function (element) {
                        $(element).show();
                    });
                    $('recurring_first_run').removeClassName('required-entry');
                    $('deploy_at').addClassName('required-entry');
                } else {

                    $('recurring_first_run').addClassName('required-entry');
                    $('deploy_at').removeClassName('required-entry');
                    $$('.saveandsendbutton').each(function (element) {
                        $(element).hide();
                    });
                }

            }
        };


        recurringControl.load();

    });


</script>
