<?php
/**
 * Copyright (C) 2020 Licentia, Unipessoal LDA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * @title      Licentia Panda - Magento® Sales Automation Extension
 * @package    Licentia
 * @author     Bento Vilas Boas <bento@licentia.pt>
 * @copyright  Copyright (c) Licentia - https://licentia.pt
 * @license    GNU General Public License V3
 * @modified   29/01/20, 15:22 GMT
 *
 */

/** @var \Licentia\Panda\Block\Adminhtml\Account\Detail $block */

$api = $block->getApi();

$account = $api->getAccountInfo();

if ($account) {
    $prefix = \Licentia\Panda\Helper\Data::getPrefixForCountry($account['country']);
}

$countries = \Licentia\Panda\Helper\Data::getCountries();
?>
<style type="text/css">
    .panda_account input[type='text'] {
        width: 100%;
        max-width: 450px;
        padding: 7px;
    }
</style>
<div class="panda_account">

    <?php if (!$account) : ?>
        <form style=" margin:0 auto;  width: 48%;"
              data-hasrequired="<?= /* @noEscape */
              __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}' method="post"
              action="<?= /* @noEscape */
              $block->getUrl('*/*/save') ?>">
            <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>">
            <input type="hidden" name="new" value="1">
            <table class="data-grid" id="log_grid_table">
                <thead>
                <tr>
                    <th class="data-grid-th center">
                        <span><?= /* @noEscape */
                            __('Add your API Key') ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="center">
                        <input type="text" required="required" placeholder="Insert your API here" name="apikey">
                    </td>
                </tr>
                <tr>
                    <td class="center">
                        <button class="primary"><span><?= /* @noEscape */
                                __('Add API Key') ?></span></button>
                    </td>
                </tr>
                </tbody>
            </table>
        </form>
        <br>
        <br>
        <br>
        <form style=" margin:0 auto;  width: 48%;"
              data-hasrequired="<?= /* @noEscape */
              __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}' method="post"
              action="<?= /* @noEscape */
              $block->getUrl('*/*/save') ?>">
            <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>">
            <input type="hidden" name="recover" value="1">
            <table class="data-grid" id="log_grid_table">
                <thead>
                <tr>
                    <th class="data-grid-th center">
                        <span><?= /* @noEscape */
                            __('Lost your API Key?') ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="center">
                        <input type="text" required="required" placeholder="Insert your ORDER email here" name="email">
                    </td>
                </tr>
                <tr>
                    <td class="center">
                        <button class="primary"><span><?= /* @noEscape */
                                __('Recover my API') ?></span></button>
                    </td>
                </tr>
                </tbody>
            </table>
        </form>

    <?php else : ?>
    <div style="width: calc(100% - 350px);  float: left">
        <form style=" margin:0 auto; max-width: 900px"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}' method="post"
              action="<?= /* @noEscape */
              $block->getUrl('*/*/save') ?>">
            <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>">
            <input type="hidden" name="update" value="1">
            <table class="data-grid" id="log_grid_table">
                <thead>
                <tr>
                    <th colspan="2" class="data-grid-th">
                        <span><?= /* @noEscape */
                            __('Account Information') ?></span></th>
                </tr>
                </thead>
                <tbody>
                <tr class="even">
                    <td width="300px;"><?= /* @noEscape */
                        __('Company') ?></td>
                    <td><input type="text" required="required" name="company"
                               value="<?= $block->escapeHtmlAttr(isset($account['company']) ? $account['company'] : '') ?>">
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('Full Name') ?></td>
                    <td><input type="text" required="required" name="name"
                               value="<?= $block->escapeHtmlAttr(isset($account['name']) ? $account['name'] : '') ?>">
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('TAX VAT ID') ?></td>
                    <td><input type="text" required="required" name="taxvat"
                               value="<?= $block->escapeHtmlAttr(isset($account['taxvat']) ? $account['taxvat'] : '') ?>"><br>
                        <small><em> A valid VAT ID (VIES validation) is required for EU customers.<br>
                                <strong> No invoices will be issued for individuals in the EU</strong></em></small>
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('Address') ?></td>
                    <td><input type="text" required="required" name="address"
                               value="<?= $block->escapeHtmlAttr(isset($account['address']) ? $account['address'] : '') ?>">
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('Zip Code') ?></td>
                    <td><input type="text" required="required" name="zipcode"
                               value="<?= $block->escapeHtmlAttr(isset($account['zipcode']) ? $account['zipcode'] : '') ?>">
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('City') ?></td>
                    <td><input type="text" required="required" name="city"
                               value="<?= $block->escapeHtmlAttr(isset($account['city']) ? $account['city'] : '') ?>">
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('Region') ?></td>
                    <td><input type="text" required="required" name="region"
                               value="<?= $block->escapeHtmlAttr(isset($account['region']) ? $account['region'] : '') ?>">
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('Country') ?></td>
                    <td>
                        <select name="country">
                            <?php foreach ($countries as $code => $country) : ?>
                                <option
                                    <?php if ($account['country'] == $code) {
                                        echo " selected ";
                                    } ?>
                                    <?= $block->escapeHtmlAttr($code) ?>><?= $block->escapeHtml($country) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('Email') ?></td>
                    <td><input data-validate="{'validate-email':true}" type="text" required="required" name="email"
                               value="<?= $block->escapeHtmlAttr(isset($account['email']) ? $account['email'] : '') ?>">
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('Cellphone') ?></td>
                    <td><input type="text" required="required" name="cellphone"
                               value="<?= $block->escapeHtmlAttr(isset($account['cellphone']) ? $account['cellphone'] : '') ?>"><br>
                    </td>
                </tr>
                <tr>
                    <td width="300px;"><?= /* @noEscape */
                        __('Newsletter') ?></td>
                    <td><input data-validate="{'validate-email':true}" type="text" name="newsletter"
                               value="<?= $block->escapeHtmlAttr(isset($account['newsletter']) ? $account['newsletter'] : '') ?>"><br>
                        <?= __('Subscribe to our newsletter. New releases and important announcements only!') ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="right"><?= __('* denotes required fields') ?>
                        <br>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="right">
                        <button class="primary"><span><?= /* @noEscape */
                                __('Update Info') ?></span></button>
                    </td>
                </tr>

                </tbody>
            </table>
        </form>
        <?php endif; ?>

    </div>
    <?php if ($account) : ?>
        <div style="width: 300px; float: right">

            <table class="data-grid">
                <tr>
                    <th class="data-grid-th"><span><?= /* @noEscape */
                            __('Account Status') ?></span></th>
                </tr>
                <tr>
                    <td class="center"><?= $block->escapeHtml($account['status_text']) ?></td>
                </tr>
            </table>
            <br>
            <table class="data-grid">
                <tr>
                    <th class="data-grid-th"><span><?= /* @noEscape */
                            __('Current API Key') ?></span>
                    </th>
                </tr>
                <tr>
                    <td class="center" style="word-break: break-all"><?= $block->escapeHtml($api->getApiKey()) ?></td>
                </tr>
            </table>
            <br>
            <table class="data-grid" id="log_grid_table">
                <thead>
                <tr>
                    <th class="data-grid-th center">
                        <span><?= /* @noEscape */
                            __('Update your API Key') ?></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="center"><a
                                href="<?= /* @noEscape */
                                $block->getUrl('*/*/*', ['newapi' => 1]) ?>">
                            <?= __('Click here to get a new API KEY.') ?></a><br/><br/>
                        <?= __('The new API Key will be sent to your cellphone and email') ?>
                    </td>
                </tr>
                </tbody>
            </table>
            <br>
            <form data-mage-init='{"validation":{}}' method="post"
                  action="<?= /* @noEscape */
                  $block->getUrl('*/*/save') ?>">
                <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>">
                <input type="hidden" name="cancelAccount" value="1">
                <table class="data-grid">
                    <tr>
                        <th class="data-grid-th">
                            <span><?= /* @noEscape */
                                __('Cancel Subscription/Delete Account') ?></span>
                        </th>
                    </tr>
                    <tr>
                        <td class="center"><em style="color: #a2514e; font-weight: bolder">
                                <?= __('This action cannot be undone') ?></em>
                        </td>
                    </tr>
                    <tr>
                        <td><input type="text" required="required" name="delete_account"><br><?= __(
                                'To cancel your subscription, please insert your API key above'
                            ) ?></td>
                    </tr>
                    <tr>
                        <td>
                            <button type="submit" name="delete_account"><?= __(
                                    'PERMANENTLY DELETE ACCOUNT'
                                ) ?></button>
                        </td>
                    </tr>
                </table>
                <br>
            </form>
        </div>
    <?php endif; ?>
</div>